"""Build the document catalog for ingestion from the two manifests:
  data/sources.yaml            — real documents (method script/manual; excluded/dropped/covered are skipped)
  data/synthetic_manifest.yaml — fictional documents generated by scripts/generate_synthetic.py
Each entry becomes a DocRecord with the metadata that will be stamped on every chunk.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml

from app.config import settings


@dataclass
class DocRecord:
    doc_id: str
    title: str
    domain: str
    region: str
    audience: str
    sensitivity: str
    origin: str                      # original | synthetic
    path: Path                       # file to parse
    kind: str                        # pdf | docx | xlsx | md
    tags: list[str] = field(default_factory=list)
    doc_code: str | None = None
    version: str | None = None
    effective_date: str | None = None
    policy_key: str | None = None
    supersedes: str | None = None
    source_url: str | None = None
    text_path: Path | None = None    # OCR sidecar or markdown extraction to parse instead of `path`

    @property
    def parse_path(self) -> Path:
        return self.text_path or self.path

    @property
    def parse_kind(self) -> str:
        if self.text_path:
            return "md"
        return self.kind


def _norm_region(r: str) -> str:
    return "global" if r in ("global", "GLOBAL") else r


def load_catalog() -> list[DocRecord]:
    raw = settings.raw_dir
    docs: list[DocRecord] = []

    src = yaml.safe_load(settings.sources_yaml.read_text(encoding="utf-8"))
    defaults = src.get("defaults", {})
    for s in src["sources"]:
        s = {**defaults, **s}
        if s["method"] in ("dropped", "covered", "excluded"):
            continue
        p = raw / s["path"]
        text_path = raw / s["text_path"] if s.get("text_path") else None
        kind = s["kind"]
        ext = p.suffix.lower().lstrip(".")
        if ext in ("pdf", "docx", "xlsx", "md"):  # manual saves may be PDFs even when the manifest says html
            kind = ext
        if kind == "html":  # fetched html pages were converted to markdown next to the html
            md = p.with_suffix(".md")
            if md.exists():
                text_path, kind = md, "md"
            else:
                continue
        if not (text_path or p).exists():
            continue
        docs.append(DocRecord(
            doc_id=s["id"], title=s["title"], domain=s["domain"], region=_norm_region(s["region"]),
            audience=s.get("audience", "public"), sensitivity=s.get("sensitivity", "public"), origin="original",
            path=p, kind=kind, tags=list(s.get("tags", [])), doc_code=s.get("doc_code"), version=str(s["version"]) if s.get("version") else None,
            effective_date=str(s["effective_date"]) if s.get("effective_date") else None, policy_key=s.get("policy_key"),
            supersedes=str(s["supersedes"]) if s.get("supersedes") else None, source_url=s.get("url"), text_path=text_path,
        ))

    syn = yaml.safe_load(settings.synthetic_manifest.read_text(encoding="utf-8"))
    for s in syn["documents"]:
        p = raw / s["path"]
        if not p.exists():
            continue
        docs.append(DocRecord(
            doc_id=s["id"], title=s["title"], domain=s["domain"], region=_norm_region(s["region"]),
            audience=s["audience"], sensitivity=s["sensitivity"], origin="synthetic",
            path=p, kind=s["format"], tags=list(s.get("tags", [])), doc_code=s.get("doc_code"),
            version=str(s["version"]) if s.get("version") else None,
            effective_date=str(s["effective_date"]) if s.get("effective_date") else None,
            policy_key=s.get("policy_key"), supersedes=str(s["supersedes"]) if s.get("supersedes") else None,
        ))
    return docs
