"""Generate the fictional (synthetic) documents into data/raw/<domain>/<region>/ next to the real ones,
write data/synthetic_manifest.yaml (ingestion metadata), and build docs/Document_Inventory.xlsx — a
reference-only workbook listing every document in the corpus and whether it is an original Kohler document
or one created by us.

Usage:
    python scripts/generate_synthetic.py            # render all + inventory
    python scripts/generate_synthetic.py --inventory-only
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from datetime import date
from pathlib import Path

import yaml
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

sys.path.insert(0, str(Path(__file__).resolve().parent))
from synthetic import content_finance, content_hr, content_legal, content_privacy_support  # noqa: E402
from synthetic.render import BANNER, RENDERERS  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
SOURCES = ROOT / "data" / "sources.yaml"
SYN_MANIFEST = ROOT / "data" / "synthetic_manifest.yaml"
INVENTORY = ROOT / "docs" / "Document_Inventory.xlsx"

ALL_DOCS = content_hr.DOCS + content_finance.DOCS + content_legal.DOCS + content_privacy_support.DOCS
META_KEYS = ["id", "doc_code", "title", "domain", "region", "audience", "sensitivity", "format", "path", "version",
             "effective_date", "policy_key", "supersedes", "owner", "tags"]


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def render_all() -> list[dict]:
    records = []
    for doc in ALL_DOCS:
        out = RAW / doc["path"]
        out.parent.mkdir(parents=True, exist_ok=True)
        RENDERERS[doc["format"]](doc, out)
        rec = {k: doc[k] for k in META_KEYS if k in doc}
        rec.update(origin="synthetic", fictional=True, size=out.stat().st_size, sha256=sha256_of(out))
        records.append(rec)
        print(f"  {doc['format']:4}  {doc['sensitivity']:10}  {doc['path']}")
    SYN_MANIFEST.write_text(
        "# Fictional documents generated by scripts/generate_synthetic.py. " + BANNER + "\n"
        + yaml.safe_dump({"generated": date.today().isoformat(), "documents": records}, sort_keys=False, allow_unicode=True),
        encoding="utf-8")
    print(f"\n{len(records)} synthetic documents written; manifest: {SYN_MANIFEST.relative_to(ROOT)}")
    return records


def build_inventory(syn_records: list[dict]) -> None:
    src = yaml.safe_load(SOURCES.read_text(encoding="utf-8"))
    defaults = src.get("defaults", {})
    rows = []
    for s in src["sources"]:
        s = {**defaults, **s}
        p = RAW / s["path"]
        status = {"dropped": "Dropped (empty page)", "covered": "Duplicate of another entry"}.get(s["method"])
        if not status:
            status = "On disk" if p.exists() else "Missing"
        text_note = "OCR text sidecar" if "ocr" in s.get("tags", []) else ""
        rows.append(["Original (Kohler / publisher)", s["id"], s["title"], s["domain"], s["region"], s.get("audience", "public"),
                     s.get("sensitivity", "public"), s["kind"].upper(), s["path"], status, s.get("version", ""),
                     s.get("effective_date", ""), s.get("policy_key", ""), s["url"], s["method"], text_note, s.get("notes", "")])
    for r in syn_records:
        rows.append(["Created by us (FICTIONAL)", r["id"], r["title"], r["domain"], r["region"], r["audience"], r["sensitivity"],
                     r["format"].upper(), r["path"], "On disk", r.get("version", ""), r.get("effective_date", ""),
                     r.get("policy_key", ""), "— generated by scripts/generate_synthetic.py", "generated", "",
                     "Fictional document for educational purposes only; not real data."])

    headers = ["Origin", "ID", "Title", "Knowledge base", "Region", "Audience", "Sensitivity", "Format", "Path (data/raw/)",
               "Status", "Version", "Effective date", "Policy key", "Source URL / generator", "Method", "Text note", "Notes"]
    wb = Workbook()
    ws = wb.active
    ws.title = "Inventory"
    ws["A1"] = "Document Inventory — reference only, not used by the application"
    ws["A1"].font = Font(bold=True, size=13)
    ws["A2"] = ("Origin = 'Original' for documents published by Kohler Co. / Kohler India / Kohler Mira / third parties "
                "(used unmodified under their terms; never committed to git). Origin = 'Created by us' for fictional "
                "documents generated for the prototype — educational purposes only, not real data.")
    ws["A2"].alignment = Alignment(wrap_text=True)
    ws.merge_cells("A2:Q2")
    ws.row_dimensions[2].height = 32
    for j, h in enumerate(headers, start=1):
        c = ws.cell(row=4, column=j, value=h)
        c.font = Font(bold=True, color="FFFFFF")
        c.fill = PatternFill("solid", fgColor="1F3864")
        c.alignment = Alignment(wrap_text=True, vertical="top")
    fill_syn = PatternFill("solid", fgColor="FFF2CC")
    for i, r in enumerate(sorted(rows, key=lambda x: (x[3], x[0], x[4], x[2])), start=5):
        for j, v in enumerate(r, start=1):
            c = ws.cell(row=i, column=j, value=v)
            c.alignment = Alignment(wrap_text=True, vertical="top")
            if r[0].startswith("Created"):
                c.fill = fill_syn
    widths = [26, 34, 56, 14, 9, 14, 12, 8, 52, 22, 10, 13, 30, 60, 10, 16, 60]
    for j, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(j)].width = w
    ws.freeze_panes = "A5"
    ws.auto_filter.ref = f"A4:{get_column_letter(len(headers))}{4 + len(rows)}"

    # Summary sheet
    sm = wb.create_sheet("Summary")
    sm["A1"] = "Documents by knowledge base and origin"
    sm["A1"].font = Font(bold=True, size=12)
    kbs = ["hr", "finance", "legal", "privacy", "support", "sustainability"]
    sm.append([])
    sm.append(["Knowledge base", "Original — on disk", "Created by us", "Total ingestable", "Restricted (local model)"])
    for c in sm[3]:
        c.font = Font(bold=True)
    tot = [0, 0, 0, 0]
    for kb in kbs:
        orig = sum(1 for r in rows if r[3] == kb and r[0].startswith("Original") and r[9] == "On disk")
        syn = sum(1 for r in rows if r[3] == kb and r[0].startswith("Created"))
        restricted = sum(1 for r in rows if r[3] == kb and r[6] == "restricted" and r[9] == "On disk")
        sm.append([kb, orig, syn, orig + syn, restricted])
        for k, v in enumerate((orig, syn, orig + syn, restricted)):
            tot[k] += v
    sm.append(["TOTAL", *tot])
    for c in sm[sm.max_row]:
        c.font = Font(bold=True)
    for col, w in zip("ABCDE", (18, 20, 16, 18, 24)):
        sm.column_dimensions[col].width = w
    INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(INVENTORY))
    print(f"inventory: {INVENTORY.relative_to(ROOT)}  ({len(rows)} rows)")


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory-only", action="store_true")
    args = ap.parse_args()
    if args.inventory_only:
        recs = yaml.safe_load(SYN_MANIFEST.read_text(encoding="utf-8"))["documents"]
    else:
        recs = render_all()
    build_inventory(recs)
    return 0


if __name__ == "__main__":
    sys.exit(main())
